### ISSUE TITLE
Catchup are not working

### ISSUE THREAD

**Issue by Ursgirishgupta** [sandeep1027/jioTvPlugin#3]
Catchup are not working for any channel, please look into and fix the same, once done please share new zip file. 

@sandeep1027 @zeffd

**Comment by sandeep1027** [comment]
> Catchup are not working for any channel, please look into and fix the same, once done please share new zip file.
> 
> @sandeep1027 @zeffd

can you share screenshot.
Note: Some channels are not working irrespect of catchup

**Comment by Ursgirishgupta** [comment]
![1675680028497](https://user-images.githubusercontent.com/123805216/216951338-9cb16003-c00c-4595-9b4e-dc0ba508ac2e.jpg)
Please have a look at attached screenshot, the channel is working fine but catchup are not. 

I am aware with the fact that few channels are not working ex .... animal Planet hindi & discovery Channel hindi i am not trying to play catchup for those, but the issue is channels working fine are not able to play the catchup.

**Comment by sandeep1027** [comment]
> ![1675680028497](https://user-images.githubusercontent.com/123805216/216951338-9cb16003-c00c-4595-9b4e-dc0ba508ac2e.jpg) Please have a look at attached screenshot, the channel is working fine but catchup are not.
> 
> I am aware with the fact that few channels are not working ex .... animal Planet hindi & discovery Channel hindi i am not trying to play catchup for those, but the issue is channels working fine are not able to play the catchup.

share kodi logs

**Comment by Ursgirishgupta** [comment]
https://paste.kodi.tv/xerisoquci

![Screenshot_2023-02-06-16-45-59-994_org xbmc kodi](https://user-images.githubusercontent.com/123805216/216958395-ce04e5ac-1042-4794-9795-c93aa1959c97.jpg)


Please have a look at the above url and attached QR code.

Note i am trying to play catchup for "News 18 India", but case is same with all others as well.

**Comment by sandeep1027** [comment]
can you test this new build: https://github.com/sandeep1027/jioTvPlugin/archive/refs/tags/fix_catchup.zip

**Comment by Ursgirishgupta** [comment]
![Screenshot_2023-02-06-23-33-30-402_org xbmc kodi](https://user-images.githubusercontent.com/123805216/217050361-b723ec00-f5cd-46e9-9189-a837d14ab4ee.jpg)
![Screenshot_2023-02-06-23-32-46-084_org xbmc kodi](https://user-images.githubusercontent.com/123805216/217050368-d0ae41cf-1ac4-4786-b2fa-b0e9ae8ef295.jpg)
![Screenshot_2023-02-06-23-32-06-093_org xbmc kodi](https://user-images.githubusercontent.com/123805216/217050376-b362b1b8-c8c8-4149-ae4b-87b5891d8510.jpg)
![Screenshot_2023-02-06-23-31-50-594_org xbmc kodi](https://user-images.githubusercontent.com/123805216/217050378-ae767e82-01d1-45b1-958f-58cbf4a41b45.jpg)

https://paste.kodi.tv/pamaketode

Getting errors now, no channels getting played.

**Comment by sandeep1027** [comment]
try this : https://github.com/sandeep1027/jioTvPlugin/archive/refs/tags/fix.zip

**Comment by Ursgirishgupta** [comment]
![Screenshot_2023-02-06-23-50-49-991_org xbmc kodi](https://user-images.githubusercontent.com/123805216/217053844-422fe9d0-cc12-4631-a895-47fbd657030f.jpg)
![Screenshot_2023-02-06-23-50-02-755_org xbmc kodi](https://user-images.githubusercontent.com/123805216/217053860-2f642bc7-6120-4f19-995d-e78d5b4da6f7.jpg)


Issue seem to fix partly only, for few channels catchup are working but still have few exception. 
Example sony entertainment HD channel is working but while playing catchup getting attached error.

**Comment by sandeep1027** [comment]
because it is from jio server...i cannt fix that  :D
