### ISSUE TITLE
Kids section not working 

### ISSUE THREAD

**Issue by mk384456** [sandeep1027/jioTvPlugin#5]
Pogo hindi,nick hindi,sonic hindi, discovery kids, history tv 18 not working because all these channels support dual audio please fix !!

if you want audio source for these channels use 
https://www.hotstar.eu.org

Open in chrome browser in pc play a dual audio channel eg history tv 18 and press f12 for inspect to open under network tab filter .aac for audio source and .m3u8 for video source

Hoping for next update thanks ☺️☺️

**Comment by sandeep1027** [comment]
unable to login there

**Comment by sandeep1027** [comment]
check the latesh build bro :)
